### ISSUE TITLE
create elastic bare metal server fails at preview

### ISSUE THREAD

**Issue by nicolasochem** [pulumiverse/pulumi-scaleway#251]
Related to https://github.com/pulumi/pulumi-terraform-bridge/issues/1231

Code:

```
    const nochemSshKey = scaleway.getAccountSshKey({
      name: "nochem",
    });
    let sshKeyId = nochemSshKey.then(key => key.id);
    // ubuntu 22.04
    new scaleway.BaremetalServer("test", {
      zone: "fr-par-2",
      offer: "EM-I210E-NVME",
      os: "96e5f0f2-d216-4de2-8a15-68730d877885",
      sshKeyIds: [sshKeyId],
      name: "nochem-test"
    });
```

Trace:

```
Diagnostics:
  scaleway:index:BaremetalServer (test):
    error: Preview failed: error reading from server: EOF

  pulumi:pulumi:Stack (pulumi-polkadot-prod):
    panic: HasAttribute on non-object Type
    goroutine 97 [running]:
    github.com/hashicorp/go-cty/cty.Type.HasAttribute({{0x0?, 0x0?}}, {0x17c62a3?, 0x203000?})
        /home/runner/go/pkg/mod/github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/object_type.go:104 +0x8b
    github.com/scaleway/terraform-provider-scaleway/v2/scaleway.getLocality(0x40d5bf?, 0xc000600001?)
        /home/runner/go/pkg/mod/github.com/scaleway/terraform-provider-scaleway/v2@v2.22.0/scaleway/helpers.go:915 +0x45
    github.com/scaleway/terraform-provider-scaleway/v2/scaleway.customizeDiffLocalityCheck.func1({0xc000a191e0?, 0xc000aa4a20?}, 0xc000aa49f0?, {0x1505b00?, 0xc000396d60?})
        /home/runner/go/pkg/mod/github.com/scaleway/terraform-provider-scaleway/v2@v2.22.0/scaleway/helpers.go:932 +0x71
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/customdiff.Sequence.func1({0x1c5a158, 0xc000126018}, 0x17d49ae?, {0x1505b00, 0xc000396d60})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230327102345-3fa930f86570/helper/customdiff/compose.go:67 +0x89
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0xc000452f30, {0x1c5a158, 0xc000126018}, 0xc000530270, 0xc000cce270, 0xc0006408e0, {0x1505b00, 0xc000396d60}, 0x0)
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230327102345-3fa930f86570/helper/schema/schema.go:699 +0x4d4
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x0?, {0x1c5a158?, 0xc000126018?}, 0xc000530270, 0xc000cce270?, {0x1505b00?, 0xc000396d60?})
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230327102345-3fa930f86570/helper/schema/resource.go:895 +0x6c
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.simpleDiff({0x0?, {0xffffffffffffffff?, 0xc000a9d4d0?, 0xe39ae9?}}, 0x15bf0a0?, 0xc000cce240?, 0xc0005301a0, 0xc000a9d538?, {{{0x1c5b038, 0xc00045c0d8}}, ...}, ...)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.53.0/pkg/tfshim/sdk-v2/provider_diff.go:87 +0x785
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Diff({0xc0000b42a0?, {0x0?, 0xc000202b00?, 0xc00052e090?}}, {0x17eb193, 0x19}, {0x0?, 0x0}, {0x1c51140, 0xc000cce270})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.53.0/pkg/tfshim/sdk-v2/provider_diff.go:63 +0x30c
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0xc000202b00, {0x1c5a1c8?, 0xc000cce120?}, 0xc0000bea50)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.53.0/pkg/tfbridge/provider.go:721 +0x41d
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x1c5a1c8, 0xc000cce120}, {0x16f4080?, 0xc0000bea50})
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.74.0/proto/go/provider_grpc.pb.go:573 +0x78
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x1c5a1c8, 0xc0002e0fc0}, {0x16f4080, 0xc0000bea50}, 0xc000558080, 0xc000556180)
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3f9
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x17866e0?, 0xc000202b00}, {0x1c5a1c8, 0xc0002e0fc0}, 0xc000562000, 0xc000641160)
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.74.0/proto/go/provider_grpc.pb.go:575 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc0007be000, {0x1c618c0, 0xc0009e6000}, 0xc000c7e000, 0xc00052ec90, 0x28e8e60, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:1337 +0xdf0
    google.golang.org/grpc.(*Server).handleStream(0xc0007be000, {0x1c618c0, 0xc0009e6000}, 0xc000c7e000, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:1714 +0xa2f
    google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:959 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:957 +0x18c

    error: preview failed
```

Thanks in advance.

**Comment by benjick** [comment]
I'm getting this error with the following code:

```ts
const mainDatabaseInstance = new scaleway.DatabaseInstance(
  "mainDatabaseInstance",
  {
    nodeType: "DB-DEV-S",
    engine: "PostgreSQL-15",
    isHaCluster: true,
    disableBackup: true,
    userName: "my_initial_user",
    password: "thiZ_is_v&ry_s3cret",
  },
);
```

**Comment by ringods** [comment]
Please file a new Github issue when this problem is not fixed in the meantime.
